### PR TITLE
Type Conversions

### PR DESCRIPTION
**Pull request by AshiqueImran**
@jamal-pb95 check please

### CODE REVIEW

**Comment by raikusy** [comment]
@AshiqueImran ভাই কিছু পরিবর্তন সাজেস্ট করা হয়েছে। আপনি কি দয়া করে এগুলি আপডেট করে দিতে পারবেন? :smile:

**Comment by AshiqueImran** [comment]
@raikusy I have been out of the town for last 4-5 days. I hope to complete the task soon. Sorry for the inconvenience.

**Comment by jamal-pb95** [comment]
Don't worry brother! this is an open-source project and we care about your personal preferences. take your time and contribute your own way. thanks to be a part of us. hope you will be back and contribute again soon! 😄 ❤️

**Pull request merged**
